export * from "./email-icon.component";
export * from "./facebook-icon.component";
export * from "./github-icon.component";
export * from "./globe-icon.component";
export * from "./instagram-icon.component";
export * from "./linkedin-icon.component";
export * from "./phone-icon.component";
export * from "./youtube-icon.component";
export * from "./tiktok-icon.component";
